version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/cdvist

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/cdvist

  redis:
    image: redis:7.2
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
