version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/cdvist
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

  celery:
    build: .
    container_name: celery_worker
    command: celery -A app.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/cdvist
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - app_network

  redis:
    image: redis:7.2
    container_name: redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge